---
# tasks file for kibana-role
- hosts: kibana
  tasks:
  - name: "Download Kibana's rpm"
    get_url:
      #https://artifacts.elastic.co/downloads/kibana/kibana-8.0.0-linux-x86_64.tar.gz
      url: "https://artifacts.elastic.co/downloads/kibana/kibana-{{ kibana_version }}-x86_64.rpm"
      dest: "/tmp/kibana-{{ kibana_version }}-x86_64.rpm"
    register: download_kibana
    until: download_kibana is succeeded
  - name: Install Kibana
    become: true
    yum:
      name: "/tmp/kibana-{{ kibana_version }}-x86_64.rpm"
      state: present
  - name: Configure kibana
    become: true
    template:
      src: kibana.yml.j2
      dest: /etc/kibana/kibana.yml
    notify: restart kibana